#!/usr/bin/env bash

set -eo pipefail

for desktoptype in plasma5; do
    for filesystem in xfs ext4 btrfs; do
        ./packer-build-desktop "$@" \
            -var "install_type=-$desktoptype" \
            -var "filesystem=$filesystem"
    done
done
