#!/usr/bin/env bash

set -eo pipefail

tar -zcf archlinux-reinstall.tar.gz ./*.txt ./*.packages ./*.sh ./etc*

echo "packer-build-desktop $*"

packer build "$@" packer-desktop.json

rm archlinux-reinstall.tar.gz
